-- MySQL Script generated by MySQL Workbench
-- sáb 24 sep 2022 17:04:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Cul_d_Ampolla
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Cul_d_Ampolla` ;

-- -----------------------------------------------------
-- Schema Cul_d_Ampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cul_d_Ampolla` ;
USE `Cul_d_Ampolla` ;

-- -----------------------------------------------------
-- Table `Cul_d_Ampolla`.`adreca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cul_d_Ampolla`.`adreca` ;

CREATE TABLE IF NOT EXISTS `Cul_d_Ampolla`.`adreca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `carrer` VARCHAR(45) NULL,
  `numero` VARCHAR(5) NULL,
  `pis` VARCHAR(2) NULL,
  `ciutat` VARCHAR(15) NULL,
  `codi_postal` VARCHAR(6) NULL,
  `pais` VARCHAR(15) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_d_Ampolla`.`proveidor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cul_d_Ampolla`.`proveidor` ;

CREATE TABLE IF NOT EXISTS `Cul_d_Ampolla`.`proveidor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `NIF` VARCHAR(10) NULL,
  `nom` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(15) NULL,
  `fax` VARCHAR(15) NULL,
  `adreca_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_proveidor_adreca_idx` (`adreca_id` ASC) VISIBLE,
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC) VISIBLE,
  CONSTRAINT `fk_proveidor_adreca`
    FOREIGN KEY (`adreca_id`)
    REFERENCES `Cul_d_Ampolla`.`adreca` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_d_Ampolla`.`muntura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cul_d_Ampolla`.`muntura` ;

CREATE TABLE IF NOT EXISTS `Cul_d_Ampolla`.`muntura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `material` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_d_Ampolla`.`ullera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cul_d_Ampolla`.`ullera` ;

CREATE TABLE IF NOT EXISTS `Cul_d_Ampolla`.`ullera` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(20) NOT NULL,
  `graduacioE` FLOAT NOT NULL,
  `graduacioD` FLOAT NOT NULL,
  `color` VARCHAR(15) NOT NULL,
  `color_vidreE` VARCHAR(15) NOT NULL,
  `color_vidreD` VARCHAR(15) NOT NULL,
  `preu` DOUBLE(7,2) NOT NULL,
  `muntura_id` INT NOT NULL,
  `proveidor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ullera_muntura1_idx` (`muntura_id` ASC) VISIBLE,
  INDEX `fk_ullera_proveidor1_idx` (`proveidor_id` ASC) VISIBLE,
  CONSTRAINT `fk_ullera_muntura1`
    FOREIGN KEY (`muntura_id`)
    REFERENCES `Cul_d_Ampolla`.`muntura` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ullera_proveidor1`
    FOREIGN KEY (`proveidor_id`)
    REFERENCES `Cul_d_Ampolla`.`proveidor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_d_Ampolla`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cul_d_Ampolla`.`client` ;

CREATE TABLE IF NOT EXISTS `Cul_d_Ampolla`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `adreca_postal` VARCHAR(60) NULL,
  `telefon` VARCHAR(15) NULL,
  `correu_electronic` VARCHAR(45) NULL,
  `data_registre` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `client_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_client1_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `Cul_d_Ampolla`.`client` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_d_Ampolla`.`empleat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cul_d_Ampolla`.`empleat` ;

CREATE TABLE IF NOT EXISTS `Cul_d_Ampolla`.`empleat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_d_Ampolla`.`comanda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cul_d_Ampolla`.`comanda` ;

CREATE TABLE IF NOT EXISTS `Cul_d_Ampolla`.`comanda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `ullera_id` INT NOT NULL,
  `empleat_id` INT NOT NULL,
  `data_comanda` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `proveidor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_factura_client1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_factura_ullera1_idx` (`ullera_id` ASC) VISIBLE,
  INDEX `fk_factura_empleat1_idx` (`empleat_id` ASC) VISIBLE,
  INDEX `fk_comanda_proveidor1_idx` (`proveidor_id` ASC) VISIBLE,
  CONSTRAINT `fk_factura_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `Cul_d_Ampolla`.`client` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_factura_ullera1`
    FOREIGN KEY (`ullera_id`)
    REFERENCES `Cul_d_Ampolla`.`ullera` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_factura_empleat1`
    FOREIGN KEY (`empleat_id`)
    REFERENCES `Cul_d_Ampolla`.`empleat` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comanda_proveidor1`
    FOREIGN KEY (`proveidor_id`)
    REFERENCES `Cul_d_Ampolla`.`proveidor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


INSERT INTO adreca (carrer,numero,pis,ciutat,codi_postal,pais) VALUES 
('carrer dels arbres','1','2','Barcelona','08900','España'),
('Calle madrid','100','8','Madrid','28009','España'),
('Calle bilbao','89','7','Bilbao','48005','España'),
('Calle sevilla','3','4','Sevilla','41011','España'),
('Calle pamplona 9','7','1','Pamplona','31009','España');

INSERT INTO proveidor (nom,NIF,telefon,fax,adreca_id) VALUES 
('Prosum','5637849B','536784897','573864890',1),
('Multiópticas','5567855C','656788657','964575347',2),
('Missandtrendy Sunglasses','56784466T','672372377','67346737',3),
('General Óptica ','34577655T','624678998','6754546899',4),
('VistaÓptica ','56722213F','68898954','9245787567',5);


INSERT INTO client (nom,adreca_postal,telefon,correu_electronic) VALUES 
('client1','carrer Balmes 234','623456778','client1@hotmail.com'),
('client2','carrer Augusta 233','546748768','client2@hotmail.com'),
('client3','carrer marittim 20','547846372','client3@gmail.com'),
('client4','carrer nou 78','829874650','client4@gmail.com'),
('client5','carrer prim','846778849','client5@hotmail.com');

INSERT INTO empleat (nom) VALUES 
('Pep'),
('Jordi'),
('Pascal'),
('Joan'),
('Artur');

INSERT INTO muntura (material) VALUES 
('metallica'),
('flotant'),
('pasta');


INSERT INTO ullera (marca,graduacioE,graduacioD,color,color_vidreE,color_vidreD,preu,muntura_id,proveidor_id)
VALUES 
('Gucci',2.1,2.5,'negre','transparent','neutre',256.99,1,1),
('Armani',1.5,1.0,'blanc','blau','blau',300.00,2,1),
('Emporio Armani',0.0,0.0,'marron','transparent','transparent',199.99,3,1),
('Rayban',1.0,1.1,'negre','gris','gris',329.99,1,2),
('Roberto Cavalli',2.5,2.0,'groc','verd','verd',450.00,3,2),
('Micael Kors',3.1,3.5,'dorat','negre','negre',279.99,3,1),
('Guess',0.5,0.5,'negre brillant','negre','negre',500.00,3,5),
('Police',0.9,0.9,'vermell','transparent','transparent',199.99,1,4),
('Lacoste',0.3,0.4,'gris','blau','blau',130.00,1,2),
('Polaroid',0.9,0.7,'beige','fumat','fumat',174.99,2,5),
('Carrera',4.0,3.9,'negre','negre brillant','negre brillant',320.00,3,4),
('Levi''s',1.0,1.0,'oro','transparent','transparent',199.99,1,3);


INSERT INTO comanda (client_id,ullera_id,empleat_id,data_comanda,proveidor_id) VALUES 
(1,1,1,'2021-01-02',1),
(5,5,5,'2021-03-22',1),
(2,1,2,'2021-01-02',2),
(4,2,2,'2022-06-09',2),
(3,2,2,'2022-11-07',1),
(1,11,4,'2022-07-16',2),
(1,12,5,'2021-04-21',3),
(2,9,2,'2021-10-30',4),
(1,3,1,'2022-07-23',3),
(2,2,2,'2022-02-22',4),
(2,7,2,'2021-11-11',1),
(2,7,2,'2022-11-01',1),
(1,8,4,'2022-11-02',1),
(5,3,5,'2022-08-22',2),
(4,4,4,'2022-12-12',3),
(3,3,3,'2022-05-05',1),
(4,4,4,'2021-01-02',1),
(1,2,4,'2022-12-13',1),
(4,3,1,'2022-01-07',2),
(5,3,1,'2022-03-11',4);

-- Llista el total de factures d'un client/a en un període determinat.
/*select count(comanda.id) from comanda where client_id = 1 
and data_comanda >= '2021-01-01' and data_comanda <= '2022-12-31'*/;


-- Llista els diferents models d'ulleres que ha venut un empleat/da durant un any.
/*select ullera.marca from ullera
inner join comanda
on comanda.ullera_id = ullera.id where comanda.empleat_id = 1 and 
comanda.data_comanda >= '2022-01-01' and data_comanda <= '2022-12-31';*/

-- Llista els diferents proveïdors que han subministrat ulleres venudes amb èxit per l'òptica.
/*select count(proveidor.id), proveidor.nom, proveidor.id from proveidor
inner join comanda
on proveidor.id = comanda.proveidor_id 
group by proveidor.nom, proveidor.id order by proveidor.id;*/

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
