-- MySQL Script generated by MySQL Workbench
-- vie 21 oct 2022 01:50:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Pizzeria` ;

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria` DEFAULT CHARACTER SET utf8mb4 ;
USE `Pizzeria` ;

-- -----------------------------------------------------
-- Table `Pizzeria`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`client` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `cognoms` VARCHAR(45) NOT NULL,
  `adreca` VARCHAR(60) NOT NULL,
  `codi_postal` VARCHAR(6) NOT NULL,
  `localitat` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(30) NOT NULL,
  `telefon` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`rol` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcio` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`botiga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`botiga` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`botiga` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `adreca` VARCHAR(60) NULL,
  `codi_postal` VARCHAR(6) NULL,
  `localitat` VARCHAR(20) NULL,
  `provincia` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`empleat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`empleat` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`empleat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(15) NOT NULL,
  `cognoms` VARCHAR(25) NOT NULL,
  `NIF` VARCHAR(10) NOT NULL,
  `telefon` VARCHAR(15) NULL,
  `rol_id` INT NOT NULL,
  `botiga_id` INT NOT NULL,
  PRIMARY KEY (`id`, `rol_id`, `botiga_id`),
  INDEX `fk_empleat_rol1_idx` (`rol_id` ASC) VISIBLE,
  INDEX `fk_empleat_botiga1_idx` (`botiga_id` ASC) VISIBLE,
  CONSTRAINT `fk_empleat_rol1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `Pizzeria`.`rol` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_empleat_botiga1`
    FOREIGN KEY (`botiga_id`)
    REFERENCES `Pizzeria`.`botiga` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`comanda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`comanda` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`comanda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_comanda` DATETIME NOT NULL,
  `entrega` VARCHAR(15) NOT NULL,
  `lliurament` DATETIME NULL,
  `empleat_id` INT NULL,
  `client_id` INT NOT NULL,
  `botiga_id` INT NOT NULL,
  PRIMARY KEY (`id`, `client_id`, `botiga_id`),
  INDEX `fk_comanda_client_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_comanda_empleat1_idx` (`empleat_id` ASC) VISIBLE,
  INDEX `fk_comanda_botiga1_idx` (`botiga_id` ASC) VISIBLE,
  CONSTRAINT `fk_comanda_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `Pizzeria`.`client` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comanda_empleat1`
    FOREIGN KEY (`empleat_id`)
    REFERENCES `Pizzeria`.`empleat` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comanda_botiga1`
    FOREIGN KEY (`botiga_id`)
    REFERENCES `Pizzeria`.`botiga` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`categoria_producte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`categoria_producte` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`categoria_producte` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`producte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`producte` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`producte` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `descripcio` VARCHAR(255) NOT NULL,
  `imatge` LONGBLOB NULL,
  `preu` FLOAT NULL,
  `categoria_producte_id` INT NOT NULL,
  `categoria_pizza` VARCHAR(50) NULL,
  PRIMARY KEY (`id`, `categoria_producte_id`),
  INDEX `fk_producte_categoria_producte1_idx` (`categoria_producte_id` ASC) VISIBLE,
  CONSTRAINT `fk_producte_categoria_producte1`
    FOREIGN KEY (`categoria_producte_id`)
    REFERENCES `Pizzeria`.`categoria_producte` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`comanda_productes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`comanda_productes` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`comanda_productes` (
  `comanda_id` INT NOT NULL,
  `producte_id` INT NOT NULL,
  `qantitat` INT NULL,
  INDEX `fk_comanda_productes_comanda1_idx` (`comanda_id` ASC) VISIBLE,
  CONSTRAINT `fk_comanda_productes_comanda1`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `Pizzeria`.`comanda` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comanda_productes_producte1`
    FOREIGN KEY (`producte_id`)
    REFERENCES `Pizzeria`.`producte` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;



INSERT INTO botiga (adreca,codi_postal,localitat,provincia) VALUES
('carrer dels arbres 1','08900','Barcelona','Barcelona'),
('Calle madrid 100','28009','Madrid','Madrid'),
('Calle bilbao 89','48005','Bilbao','Bilbao'),
('Calle sevilla 3','41011','Sevilla','Sevilla'),
('Calle pamplona 9','31009','Pamplona','Pamplona');

INSERT INTO rol (descripcio) VALUES 
('cuiner'),
('repartidor');

INSERT INTO empleat (nom,cognoms,NIF,telefon,rol_id,botiga_id) VALUES
('Pep','Blanco Castillo','46554231G','675553222',1,2),
('Jordi','Garcia Romero','56781221F','677536898',2,2),
('Joan','Sanchez Casanova','54333218K','655544332',2,1),
('Marc','Puig Gomez','511127818K','678654332',1,4);


INSERT INTO client(nom,cognoms,adreca,codi_postal,localitat,provincia,telefon) VALUES
('Jordi','Garcia Castillo','Calle nueva 21','08911','Badalona','Barcelona','654436767'),
('Ana','Sanchez Paz','Calle del mar 1','08133','Barcelona','Barcelona','678644788'),
('Marc','Casanova Gil','Calle primera 8','08977','Sant Cugat','Barcelona','678754467');





INSERT INTO categoria_producte (categoria) VALUES
('pizzes'),
('hamburgueses'),
('begudes');

INSERT INTO producte(nom,descripcio,imatge,preu,categoria_producte_id,categoria_pizza) VALUES
('Big Mac','La perfección hecha hamburguesa que te hace agua la boca comienza con dos patties de 100% carne y la salsa Big Mac',
LOAD_FILE(''),4.99,1,NULL),
('McDouble','La McDouble®, una hamburguesa doble y clásica de McDonald’s, incluye dos patties de 100% pura carne sazonados con una pizca de sal y pimienta',
LOAD_FILE(''),5.99,1,NULL),
('Super Pepperoni','Salsa de tomate natural, doble de pepperoni y extra de queso mozzarella.',LOAD_FILE(''),12.99,2,'Tomate'),
('Seis quesos','Mezcla de seis quesos (provolone, parmesano,romano, fontina, asiago y mozzarella',LOAD_FILE(''),14.99,2,'Blanca'),
('Coca-Cola','Coca-Cola Sabor Original botella 500ml y 1L.',LOAD_FILE(''),2.99,2,NULL),
('Fanta naranja','Fanta Naranja botella 500ml y 1L.',LOAD_FILE(''),2.99,2,NULL);


INSERT INTO comanda (data_comanda,entrega,lliurament,empleat_id,client_id,botiga_id) VALUES
('2022-10-01','domilici','2022-10-01 21:15:34',1,3,1),
('2022-02-11','recollir',NULL,NULL,1,1),
('2021-06-13','recullir',NULL,NULL,2,2),
('2022-01-01','domicili','2022-01-01 20:12:45',2,3,1),
('2022-01-11','domicili','2022-01-11 21:52:45',2,1,2),
('2022-03-30','domicili','2022-03-30 21:00:00',2,1,1);

INSERT INTO comanda_productes(comanda_id,producte_id,qantitat) VALUES
(1,2,2),
(1,3,2),
(2,4,3),
(2,2,3),
(2,3,3),
(3,3,1),
(4,5,2),
(4,5,2),
(5,4,2),
(5,5,2),
(6,5,3),
(6,4,3),
(6,5,3);






-- Llista quants productes de categoria 'Begudes' s'han venut en una determinada localitat.
/*SELECT count(producte_id) FROM comanda_productes AS cp INNER JOIN comanda AS c ON c.id = cp.comanda_id INNER JOIN client ON c.client_id = client.id WHERE client.localitat = 'Badalona' AND cp.producte_id = 3;*/
-- Llista quantes comandes ha efectuat un determinat empleat/da.
/*SELECT count(c.id) FROM comanda AS c WHERE c.empleat_id = 2;*/


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
